server:
  port: 8083
spring:
  application:
    name: basketservice
  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka
#    instance:
#    preferIpAddress: true
#spring:
#  application:
#    name: taskservice